openapi: 3.0.3
info:
  title: Swagger Spring boot demo
  version: 0.0.1
externalDocs:
  description: Find out more about Swagger
  url: http://swagger.io
tags:
  - name: greeting
    description: First demo API
paths:
  /greeting:
    get:
      tags:
        - greeting
      summary: A greeting endpoint
      description: Returns a greeting
      operationId: getGreeting
      responses:
        '200':
          description: A string greeting
          content:
            text/plain:
              schema:
                type: string
