services:
  app:
    build:
      context: .
      dockerfile: Dockerfile-local
    ports:
      - 4001:4001
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://host.docker.internal:5433/mydatabase
      SPRING_DATASOURCE_USERNAME: myuser
      SPRING_DATASOURCE_PASSWORD: secret
    depends_on:
      - db

  db:
    build:
      context: .
      dockerfile: Dockerfile.postgres
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - 5433:5432
    restart: unless-stopped

volumes:
  postgres-data: