services:
  postgres:
    image: 'postgres:16'
    environment:
      - 'POSTGRES_DB=mydatabase'
      - 'POSTGRES_PASSWORD=secret'
      - 'POSTGRES_USER=myuser'
    ports:
      - '5431:5432'
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
