FROM openjdk:17-alpine AS builder

RUN apk --no-cache add make

# Set working directory
WORKDIR /app

# Copy built JAR from the builder stage
COPY . .

ENV DEMO_ENV=local

RUN ./gradlew build -x test --no-daemon

FROM openjdk:17-alpine

WORKDIR /app

COPY --from=builder /app/build/libs/spring-boot-demo-local.jar /app/spring-boot-demo-local.jar

# Expose the port
EXPOSE 4001

# Run the application
CMD ["java", "-Dspring.profiles.active=local", "-jar", "spring-boot-demo-local.jar"]
